### PR TITLE
Override event_loop from asyncio

### PR DESCRIPTION
**Pull request by chris-sanders**
I can't find any way for plugins to choose their order of loading. You can monkey patch the asyncio plugin from the operator plugin though.

### CODE REVIEW

**Comment by johnsca** [comment]
There are [explicit tests upstream](https://github.com/pytest-dev/pytest-asyncio/blob/master/tests/async_fixtures/test_async_fixtures_scope.py) to ensure that this usage works, so I'm confused as to why the monkey patching would be needed.  It also looks like this [may be a regression with 0.14](https://github.com/pytest-dev/pytest-asyncio/issues/171), possibly because of the changed mentioned in [this bug](https://github.com/pytest-dev/pytest-asyncio/issues/168).

**Comment by Cynerva** [comment]
> There are explicit tests upstream to ensure that the scope change pattern works

Yeah, but they're testing it in a test_*.py file which is guaranteed to have pytest-asyncio loaded before it runs.

I think the problem here is that sometimes pytest-operator loads *before* pytest-asyncio, and when that happens, pytest-operator's module-scoped event_loop fixture gets overridden by the pytest-asyncio default event_loop fixture.

Plugin load order is partially defined, but [not well defined between plugins discovered via setuptools entrypoints](https://docs.pytest.org/en/stable/writing_plugins.html#plugin-discovery-order-at-tool-startup) and [not controllable by plugin authors](https://github.com/pytest-dev/pytest/issues/935).

Currently, the monkey-patch in this PR is the only way I see to fix this at the plugin level. Nasty as it is, it makes it so the plugin load order doesn't matter.

The other solution I see, short of rearchitecting this whole project, is to require users of pytest-operator to invoke pytest with `-p pytest-asyncio`, guaranteeing pytest-asyncio loads first.

**Comment by johnsca** [comment]
Hrm.  If the pytest-asyncio isn't discovered and registered yet, I wonder if the monkey patch could potentially fail?  Another possible approach would be to leverage the [pytest_plugin_registered hook](https://docs.pytest.org/en/stable/reference.html#_pytest.hookspec.pytest_plugin_registered), but I'm not sure if that would be cleaner or not.

**Review by johnsca — APPROVED** [review]
I poked around with the hook and it doesn't seem to help with managing fixture precedence. Even blocking the plugin manually registering it later doesn't seem affect the fixtures. So I guess the monkey patch is the only option.

**Comment by johnsca** [comment]
Released as 0.6.1

**Pull request merged**
