### PR TITLE
Add elapsed time log to key steps (#59)

### PR DESCRIPTION
**Pull request by paulomach**
## Issue

Add elapsed time log information to key steps.

## Testing

Test can be done by triggering integration tests, i.e. `tox -e integration`

### CODE REVIEW

**Comment by ca-scribner** [comment]
closes #59

**Review by stonepreston — DISMISSED** [review]
LGTM

**Comment by stonepreston** [comment]
@paulomach it seems something might have gone wrong with the GH actions and there is not a way to trigger the workflow for your PR. Would you mind closing this PR and opening a new one so we can get the test suite running?

**Comment by paulomach** [comment]
@stonepreston , [new pr](https://github.com/charmed-kubernetes/pytest-operator/pull/61)

**Pull request closed without merging**
