### PR TITLE
Teardown reliability

### PR DESCRIPTION
**Pull request by addyess**
Attempting to address https://github.com/charmed-kubernetes/pytest-operator/issues/72

### CODE REVIEW

**Comment by ca-scribner** [comment]
I wonder why this has suddenly started popping up (I've talked to three people in the last week that hit this).  If it is a teardown problem, it feels like the recent changes to pytest-operator shouldn't have made it worse, so maybe there's also been a recent change to juju that has caused the increased rate of problems?

**Comment by ca-scribner** [comment]
Nevermind ignore my previous comment - pinning to <0.17 fixes things so ...

**Comment by addyess** [comment]
the biggest change in this process is that the `ops_test.plugin.forget_model` now waits for a model to tear down rather than just issue the command to "Destroy the model" without the waiting.  I think there's an exception being raised in the `waiting for teardown` code that isn't being caught which results in test errors in the clean up of `ops_test`

**Comment by addyess** [comment]
This other PR (https://github.com/charmed-kubernetes/kubernetes-metrics-server-operator/pull/1) is using this branch of pytest-operator to test the waters

**Comment by addyess** [comment]
@ca-scribner I've seen this seems to resolve the test teardown issues.  Mind a review?

**Comment by ca-scribner** [comment]
Seems to be working in [this test PR](https://github.com/canonical/mlflow-operator/runs/6102695309?check_suite_focus=true) that was originally hitting the same issue

**Review by ca-scribner — APPROVED** [review]
lgtm.  Seems to fix the problem across at least 3 broken CIs

**Pull request merged**
